services:
  db:
    image: postgres:15-alpine
    container_name: bizi_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: bizi_web
    # --- CAMBIO IMPORTANTE ---
    # Hemos borrado 'command:'. Ahora el Dockerfile y entrypoint.sh deciden qu√© ejecutar.
    volumes:
      - ./src:/app
      - static_volume:/app/staticfiles
    ports:
      - "127.0.0.1:8000:8000"

    env_file:
      - .env
    depends_on:
      - db
    restart: always

  monitor:
    build: .
    container_name: bizi_monitor
    # Aqu√≠ S√ç mantenemos el command porque queremos ejecutar una tarea espec√≠fica
    # y no el servidor web.
    command: python manage.py iniciar_monitor
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - db
      - web
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4



  nginx:
    image: nginx:1.25-alpine
    container_name: bizi_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"  # <--- A√ëADIR PUERTO 443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
      # üëá A√ëADIR ESTOS DOS VOL√öMENES NUEVOS
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - web

  # üëá NUEVO SERVICIO
  certbot:
    image: certbot/certbot
    container_name: bizi_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot

volumes:
  postgres_data:
  static_volume:

