services:
  db:
    image: postgres:15-alpine
    container_name: bizi_db
    # CAMBIO CLAVE: Usamos env_file en lugar de environment
    # Así es igual que en Producción y no dependes de variables de tu shell
    env_file:
      - .env
    ports:
      # Mantenemos el 5433 externo para que no choque con tu Postgres local si tienes uno
      # En AWS este puerto estará abierto en el contenedor, pero cerrado por el Firewall. No pasa nada.
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  web:
    build: .
    container_name: bizi_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    restart: always

  monitor:
    build: .
    container_name: bizi_monitor
    command: python manage.py iniciar_monitor
    volumes:
      - ./src:/app
    env_file:
      - .env
    depends_on:
      - db
      - web
    restart: always
    dns:
      - 8.8.8.8
      - 8.8.4.4

volumes:
  postgres_data: